# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: research.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresearch.proto\"W\n\x08Research\x12\x12\n\x05query\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05\x66\x61\x63ts\x18\x02 \x03(\t\x12\x13\n\x06source\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_queryB\t\n\x07_sourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'research_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESEARCH']._serialized_start=18
  _globals['_RESEARCH']._serialized_end=105
# @@protoc_insertion_point(module_scope)
